apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
spec:
  selector:
    matchLabels:
      app: nginx
  replicas: 1
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: sunilkumarchandru/nginx:latest
        ports:
        - containerPort: 80
        - containerPort: 443
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-svc
spec:
  type: NodePort
  ports:
  - name: http
    port: 80
    protocol: TCP
#    nodePort: 31033
    targetPort: 80
  - name: https
    port: 443
    protocol: TCP
#    nodePort: 31036
    targetPort: 443
  selector:
    app: nginx
